### PR TITLE
Move report generation to background process

### LINKED ISSUE #106: Run reports in the background
The main testdouble database is now large enough to error on a single heroku dyno due to the 30s timeout.

In the meantime, reports can be run locally as a workaround with:

```
$ ./script/production_backup.sh
# configure development to point to present_backup...
$ rails s
```

But in the future we should implement cost-effective queue/background task for each of the reports

### PR DESCRIPTION
**Pull request by danthompson**
- Added tests for report generation behavior.
- Updated to use truncation for fixtures when dealing with capybara/phantomjs weirdness.
- Setup ActiveJob with SuckerPunch to process jobs in application process.
- Setup mailer for delivery of reports with custom template paths for views.
- Updated the phantomjs version to the latest so as to avoid random/memory errors.

More details in commits. I could keep going, but wanted to move on to other issues and where this sits it solves the problem. Also, if anyone has thoughts, I'd be happy to hear them.

Fixes #106

### CODE REVIEW

**Comment by searls** [comment]
What'll this cost to run?

**Comment by searls** [comment]
I ask b/c the reason I made it synchronous to start was because I was too cheap to pay $X/month for it. I think we're running Present on just-above-free-tier dyno now b/c of the database size.

**Comment by danthompson** [comment]
@searls ... $0.00

**Comment by searls** [comment]
ok fine just send it to expensify i guess

**Comment by searls** [comment]
I only skimmed it but seems LGTM -- ready?

**Comment by danthompson** [comment]
extremely ready.

**Pull request merged**
