### PR TITLE
Add manually invoiced projects

### PR DESCRIPTION
**Pull request by searls**
When we generate these invoices, they'll remain vague about notes/subject and leave off any line items. This way we'll have a cue that the invoice needs to be filled out manually.

### CODE REVIEW

**Comment by searls** [comment]
cc / @tkaufman

**Comment by searls** [comment]
Note that I def broke the test setup and need to check this out

**Comment by searls** [comment]
also, thanks @tinney!

**Comment by tkaufman** [comment]
I think this would be good but it's less than 5% of our use.

**Pull request merged**
